name: Send WRS Periodically

on:
  schedule:
    - cron: '0 1 * * 1'  # every hour on the hour (UTC)
  workflow_dispatch:      # allows manual triggering from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run the script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_APP_PW: ${{ secrets.GOOGLE_APP_PW }}
        run: |
          python main.py
