name: My Workflow with Custom Variables

on: [push]
env:
  GOOGLE_API_KEY: ${{ vars.GOOGLE_API_KEY }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use variables
        # Step-level variable
        run: |
          echo "API Key: $GOOGLE_API_KEY"